### ISSUE TITLE
Attribute enum vs Attributes class

### ISSUE THREAD

**Issue by mgoris** [gurpsdomain/gurpsdomain#19]
The relation between the Attribute enum and the Attributes class seems to be strange.
I feel we should refactor both, based on good decisions.
I wonder if more logic could be added to the enum rather than the class?
Input on the direction please...
@dvberkel @pebeling

**Comment by dvberkel** [comment]
Does it?

`Attribute` represent a single attribute and `Attributes` represent the collection of attributes and their specific values. To me they serve different purposes, but should both exist.

One could argue over the name, but on that note I do not have a better suggestion.

**Comment by mgoris** [comment]
Agreed. But would it then be a good idea to add all the logic on the single attribute ( i.e. enum instance) to the actual enum class implementation? Viz. the calculation of 'attribute' BASIC_SPEED for example?

**Comment by dvberkel** [comment]
That depends. First of all, from a code stand point, do all `Attribute` adhere to a common interface? If so, go ahead implement the interface for each `Attribute`. If not, best not start doing it just yet.

Second, and `BASIC_SPEED` is a good example, do these calculation not depend on `Attributes` instead of a single `Attribute`?

Havind said that, I do agree that `Attributes` is missing some abstraction. But I am not sure what is missing. Let's first see how it will be used.

**Comment by mgoris** [comment]
Agreed. Unfortunately, finding out what is missing over time will result in some FIXME's that will indicate where the current implementations and choices hurt us. But so be it.

**Comment by dvberkel** [comment]
Meh, we will see
